//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task2_DB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public int MarkId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<byte> Mark1 { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
